// やりたいことリストの初期データ
// done: 元のリストで既にチェック済み（[x]）だった項目は true
const TODO_ITEMS = [
  { text: "しらたま", done: false },
  { text: "三軒茶屋（香港麺新記、いざかやほしぐみ、オモウツボ、中華らんたな、豚とバラの日々", done: false },
  { text: "草津", done: false },
  { text: "猫カフェ", done: false },
  { text: "清澄白河（clann by the river、東京都美術館", done: false },
  { text: "押上", done: false },
  { text: "パン屋さん（Cream pand bakers代官山、equal", done: false },
  { text: "ケーキ屋さん（アムストラムグラム恵比寿店、", done: false },
  { text: "スパ🧖🧖‍♀️（タイムズスパレスタ、スパラクーア、庭の湯）", done: false },
  { text: "蔦屋カフェ", done: false },
  { text: "スタバリザーブロースタリー", done: false },
  { text: "博物館", done: false },
  { text: "美術館", done: false },
  { text: "クラフトビール（BULVAR TOKYO", done: false },
  { text: "ワイン", done: false },
  { text: "日本酒", done: false },
  { text: "動物園", done: false },
  { text: "ホカンス（グランドニッコー東京ベイ舞浜、由縁、アフヌンあるところ、8月にやります", done: false },
  { text: "星野リゾートに泊まりたい！）", done: false },
  { text: "プライベートサウナ（アカサカサウナ、SAUNA&co.、サウナランド浅草、KUDOCHI 銀座）", done: false },
  { text: "等々力渓谷（夏）", done: false },
  { text: "服巡り（渋谷、新宿、中目黒、代官山、表参道）", done: false },
  { text: "インテリアショップ巡り（青山）", done: false },
  { text: "昭和記念公園", done: false },
  { text: "渋谷スカイ", done: false },
  { text: "ボードゲームカフェ", done: false },
  { text: "神泉（ANDs.、かしおビストロバンバン）", done: false },
  { text: "ゲーセンでメダルゲームしたい😜", done: false },
  { text: "パンケーキ作る", done: false },
  { text: "日光", done: false },
  { text: "どっちかの家でひたすらドラマか映画を見る　⭐︎", done: false },
  { text: "代々木上原＋代々木公園🏸", done: false },
  { text: "大阪（USJ）", done: false },
  { text: "日比谷", done: false },
  { text: "上野（アメ横）", done: false },
  { text: "青山シャンウェイ", done: false },
  { text: "直島", done: false },
  { text: "屋久島", done: false },
  { text: "海が綺麗な島", done: false },
  { text: "北海道", done: false },
  { text: "韓国", done: false },
  { text: "ヨーロッパ", done: false },
  { text: "福岡", done: false },
  { text: "長崎", done: false },
  { text: "沖縄", done: false },
  { text: "しゃぶしゃぶ", done: false },
  { text: "リンクコーデ？したい（まずはユニクロで）", done: false },
  { text: "お揃いのアクセ作りたい", done: false },
  { text: "深大寺", done: false },
  { text: "美味しい天ぷら（尾張屋", done: false },
  { text: "カツどん　瑞兆（渋谷）", done: false },
  { text: "やんも（南青山）", done: false },
  { text: "自由丁（蔵前）", done: false },
  { text: "ハロウィンパーティー", done: false },
  { text: "ジンギスカン（松尾ジンギスカン　渋谷パルコ店）", done: false },
  { text: "あいかのメガネ買いに行く（Re:See気になる👓）", done: false },
  { text: "デジタルデトックス（スマホデトックス）", done: false },
  { text: "六本木ヒルズクリスマスマーケット（12/25）", done: false },
  { text: "オルセー美術館所蔵　印象派（-2/15）", done: false },
  { text: "カラオケ", done: false },
  { text: "新大久保", done: false },
  { text: "トラットリアグランボッカ（ポップオーバー食べれる　神楽坂）", done: false },
  { text: "ポケパークカントー", done: false },
  { text: "HANAのライブ😢→まだ？", done: false },
  { text: "防災セット揃える会　7/4候補", done: false },
  { text: "朝ランニング", done: false },
  { text: "北海道&沖縄酒場　シブネコ", done: false },
  { text: "POINT ET LIGNE", done: false },
  { text: "ハリーポッター", done: false },
  { text: "flour + water中目黒（https://youtu.be/z2AS1TOyu7E?si=EJp869dE8Xh_P9HE）", done: false },
  { text: "お台場レインボー花火2026", done: false },
  { text: "Pizzeria e Trattoria da ISA(https://youtu.be/ffwau4UFMMY?si=zXHqHTujbe6IfQ0P)", done: false },
  { text: "静岡旅行", done: false },
  { text: "井の頭公園", done: false },
  { text: "喫茶サテラ", done: false },
  { text: "美味しいパスタをつくる", done: false },
  { text: "ミネストローネをつくる", done: false },
  { text: "シチューをつくる", done: false },
  { text: "あいかの携帯プラン見直し", done: false },
  { text: "ふるさと納税パーティー", done: false },
  { text: "THE CITY BAKERY のレストラン", done: false },
  { text: "特急ラビューで秩父に行く", done: false },
  { text: "大山飲み", done: false },
  { text: "倉敷", done: false },
  { text: "キッシュ　⭐︎", done: false },
  { text: "WOODBERRY", done: false },
  { text: "ランドーズ　池袋", done: false },
  { text: "ポップコーン", done: false },
  { text: "パフェ作る", done: false },
  { text: "江ノ島水族館", done: false },
  { text: "お祭り", done: false },
  { text: "卓球", done: false },
  { text: "ビリヤード", done: false },
  { text: "モルック", done: false },
  { text: "アート教室", done: false },
  { text: "手持ち花火", done: false },
  { text: "キャンドル作り", done: false },
  { text: "お家イタリアン（パスタ、アヒージョ、カプレーゼ、スープ、ワイン）", done: false },
  { text: "立川", done: false },
  { text: "新座温泉", done: false },
  { text: "プラネタリウム", done: false },
  { text: "元町中華街", done: false },
  { text: "みなとみらい", done: false },
  { text: "かこさとし展（https://www.kanabun.or.jp/exhibition/28174/）", done: false },
  { text: "kurumicco factory（横浜ハンマーヘッド）", done: false },
  { text: "千川", done: false },
  { text: "謎解き", done: false },
  { text: "平和台", done: false },
  { text: "switch", done: true },
  { text: "帽子買いに行く（CA4LA）&PHILOCOFFEA&PRIVATE EYES & TRACKERS & HOKA", done: true },
  { text: "千乃鶴　志木店", done: true },
  { text: "OGAWA COFFEEE", done: true },
  { text: "学芸大学", done: true },
  { text: "コロッケをつくる", done: true },
  { text: "ブックカフェ（ツタヤ ブックストア 丸の内 シェアラウンジ、パーソナル ラウンジ 丸善の三階、The library lounge 、森の図書館）", done: true },
  { text: "折り紙", done: true },
  { text: "美味しいトンカツ屋", done: true },
  { text: "城崎温泉　夏か秋どう？☺️→秋に行こう🍂", done: true },
  { text: "Art bar", done: true },
  { text: "自由が丘（timeless comfort、onibus", done: true },
  { text: "犬カフェ　7/4候補", done: true },
  { text: "下北沢", done: true },
  { text: "抹茶（古桑庵", done: true },
  { text: "餃子作る　⭐︎", done: true },
  { text: "京都", done: true },
  { text: "トイストーリー　7/19？", done: true },
  { text: "ジンギスカン　なかむら", done: true },
  { text: "ランタン　池尻大橋　⭐︎", done: true },
  { text: "YONA YONA WORKS 恵比寿東口", done: true },
  { text: "武蔵小山商店街（Lily's Cafe→林試の森公園→商店街パルム）", done: true },
  { text: "（お揃い？の）スニーカーを買う", done: true },
  { text: "Wicked 2 ⭐︎", done: true },
  { text: "タコスパーティー🌮", done: true },
  { text: "みずほ台中央公園", done: true },
  { text: "劇団四季", done: true },
  { text: "アドミュージアム東京", done: true },
  { text: "ピクニック（サンドイッチ、バトミントン）", done: true },
  { text: "銭湯（文化浴泉、改良湯）", done: true },
  { text: "皇居付近散歩", done: true },
  { text: "ディズニーシー", done: true },
  { text: "音楽フェス", done: true },
  { text: "なんかの食べ物フェス", done: true },
  { text: "ふるさと納税何買うかを考える", done: true },
  { text: "川越（Brighton Cafe、cafe ANDON、", done: true },
  { text: "ディズニーランド", done: true },
  { text: "金沢", done: true },
  { text: "横浜（faro terraceキャンドルスタジオ、みなとみらい、山下公園、元町中華街、トムとジェリー展🐱🐭）", done: true },
  { text: "スコーン", done: true },
  { text: "コーヒー（STREAMER COFFEE COMPANY NAKAMEGURO）", done: true },
  { text: "代官山", done: true },
  { text: "水族館", done: true },
  { text: "神楽坂（紀の善、神楽坂おいしんぼ、ASADOR EL BUEY、CAFE & BAR 1363", done: true },
  { text: "ハンバーグ作る", done: true },
  { text: "お台場", done: true },
  { text: "蔵前（道具屋ノボリ、イーストサイドトーキョー、pretty good🍩、とろけるハンバーグ福よし、カキモリ、ウグイスビル", done: true },
  { text: "I'm donut", done: true },
  { text: "おしゃモーニング（RIVER SIDE CLUB、Breakfast Club Tokyo、コメダ", done: true },
  { text: "月島（もんじゃ）", done: true },
  { text: "NEWoman高輪", done: true },
  { text: "納豆工房せんだい", done: true },
  { text: "フレンチトースト作るor食べ行きたい", done: true },
  { text: "クリスマスパーティー（リゾット、ヘクセンハウス、ケンタッキー、", done: true },
  { text: "あいかの誕生日（何したい？）（今気づいたらぶ🥰考えとく！）", done: true },
  { text: "鍋", done: true },
  { text: "すき焼き", done: true },
  { text: "丸の内イルミ", done: true },
  { text: "大絶滅展", done: true },
  { text: "年始", done: true },
  { text: "ズートピア1？みる", done: true },
  { text: "ズートピア2みる", done: true },
];
